language: ruby
rvm:
  - 2.3.0
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - "psql -c 'create database x0y0_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
