language: ruby
rvm:
  - 2.5.1
env:
  - DISPLAY=:99.0 USE_FIREFOX=1 MOZ_HEADLESS=1
addons:
  firefox: latest
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - "psql -c 'create database x0y0_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'sh -e /etc/init.d/xvfb start'
