defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: x0y0
  password: x0y0
  host: localhost
  port: 5432

development:
  <<: *defaults
  database: x0y0_development

test:
  <<: *defaults
  database: x0y0_test
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'x0y0' %>
  password: <%= ENV['TRAVIS'] ? '' : 'x0y0' %>

production:
  <<: *defaults
  database: x0y0_production
